# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11b5e57f51134e9e3e4993aa44ec3b6b40d157a0e7c21424c0be0a545e1d58f10d7573ac6ab436e9130ea28b0150b9052ca2bf968703b117e0a62d48b279fdaf

test:
  secret_key_base: ce96ea1edcc0acc8ee10a79a0f048e579c674a2c8284bd9952461896931d7bceac114bba4b2cf5e89bf86b01e3cb0c9d102a2ff8191b39594ca34b3b43fea249

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
